# Generated by Django 3.2.4 on 2022-10-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='description_seo',
            field=models.TextField(default=555),
            preserve_default=False,
        ),
    ]
