# Generated by Django 3.2.4 on 2022-10-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_session_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='positions',
            field=models.JSONField(default='{}'),
        ),
    ]
