# Generated by Django 3.2.4 on 2022-10-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_session_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='positions',
        ),
        migrations.AddField(
            model_name='hall',
            name='positions',
            field=models.JSONField(default=dict),
        ),
    ]
