# Generated by Django 3.2.4 on 2022-10-05 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_seo', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='pages/other')),
                ('edit', models.BooleanField(default=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery_seo.image_gallery')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gallery_seo.seo')),
            ],
        ),
        migrations.DeleteModel(
            name='Other_page',
        ),
    ]
