# Generated by Django 4.0.6 on 2022-08-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('map', models.CharField(max_length=100)),
                ('using', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=100)),
                ('type_3d', models.BooleanField(default=False)),
                ('type_2d', models.BooleanField(default=False)),
                ('type_imax', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=200)),
                ('keywords', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('price', models.FloatField(default=100.0)),
                ('film', models.ManyToManyField(to='main.film')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('date_reg', models.DateField()),
                ('date_hb', models.DateField()),
                ('password', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('sex', models.BooleanField(default=True)),
                ('card', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('date_buy', models.DateTimeField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.show')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('banner', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='main.image')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='plan', to='main.image')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='main.seo')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.show')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ManyToManyField(to='main.image')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='banner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='main.image'),
        ),
        migrations.AddField(
            model_name='film',
            name='seo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='main.seo'),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.contact')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='main.seo')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.image'),
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('condition', models.TextField()),
                ('phone', models.CharField(max_length=100)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='banner', to='main.image')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.image')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.room')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='main.seo')),
            ],
        ),
    ]
