# Generated by Django 4.0.7 on 2022-08-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cinema_gallery_contact_gallery_film_gallery_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={},
        ),
    ]
