# Generated by Django 4.1 on 2022-08-31 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_gallery_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='date_buy',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='position',
        ),
    ]
