# Generated by Django 3.2.4 on 2022-10-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firefox', models.IntegerField(default=0)),
                ('chrome', models.IntegerField(default=0)),
                ('safari', models.IntegerField(default=0)),
                ('browser', models.IntegerField(default=0)),
                ('linux', models.IntegerField(default=0)),
                ('windows', models.IntegerField(default=0)),
                ('os', models.IntegerField(default=0)),
            ],
        ),
    ]
