# Generated by Django 3.2.4 on 2022-10-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminLte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='ie',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='opera',
            field=models.IntegerField(default=0),
        ),
    ]
